language: ruby
rvm:
  - 2.3.0

addons:
    postgresql: "9.6"

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database iraps_travis_test;' -U postgres  
